"""
Artifact Generator
"""
import os
import inspect # Used to grab standard lib source if needed, but here we read files

# Hardcoded paths relative to project root
PATHS = {
    "context": "profound2001/runtime/context.py",
    "pattern": "profound2001/core/pattern.py",
}

class Bundler:
    def bundle(self, pattern_name: str, output_path: str, mcp):
        # 1. Resolve Pattern Path
        if pattern_name in mcp._registry:
            # This is a bit hacky, we need the file path of the registered class
            import inspect
            cls = mcp._registry[pattern_name]
            pattern_file = inspect.getfile(cls)
        else:
            raise ValueError(f"Pattern {pattern_name} not found in registry")

        # 2. Read Components
        content = "# PROFOUND 2001 STANDALONE ARTIFACT\n\n"
        
        # Context
        with open(PATHS["context"], 'r') as f:
            content += f.read() + "\n\n"
            
        # Pattern Base - remove imports that might break standalone
        with open(PATHS["pattern"], 'r') as f:
            lines = f.readlines()
            # Filter internal imports
            clean_lines = [l for l in lines if "profound2001" not in l]
            content += "".join(clean_lines) + "\n\n"
            
        # Specific Pattern
        with open(pattern_file, 'r') as f:
            lines = f.readlines()
            clean_lines = [l for l in lines if "profound2001" not in l]
            content += "".join(clean_lines) + "\n\n"
            
        # 3. Add Bootloader
        content += f"""
if __name__ == "__main__":
    print("--- Artifact Boot: {pattern_name} ---")
    ctx = Context()
    p = {cls.__name__}()
    p.execute(ctx)
    print("--- Finished ---")
"""
        
        # 4. Write
        with open(output_path, 'w') as f:
            f.write(content)
        print(f"Bundled: {output_path}")

    def generate_readme(self, pattern_name: str, output_dir: str):
        """Generates documentation for the artifact."""
        readme = f"""# {pattern_name.capitalize()} Artifact
        
## Description
Generated by Profound 2001.

## Usage
Run the standalone script:
```bash
python {pattern_name}.py
```

## Manifest
- Core logic: {pattern_name}.py
- Context Runtime included.
"""
        import os
        path = os.path.join(output_dir, "README.md")
        with open(path, "w") as f:
            f.write(readme)
        print(f"Docs generated: {path}")
